site_name: "Crypto Wallet Help Center"
site_description: "Guides and support for popular crypto wallets like Trust Wallet, Zengo, Ledger, and more."
site_author: "shivam Sharma"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Wallet Support:
      - Trust Wallet Support: trust-wallet-support.md
      - Zengo Wallet Support: zengo-wallet-support.md
      - Ledger Wallet Support: ledger-wallet-support.md
